# -*- coding: utf-8 -*-
"""Vis2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQICeoO-sfZqt1p8E9kelN_7jCT2oZD3
"""

from urllib.request import urlopen
import json

f = 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
with urlopen(f) as response: counties = json.load(response)
#counties["features"][0]

import pandas as pd
f1 = "https://raw.githubusercontent.com/uwdata/bayesian-surprise/master/Paper%20Code%20and%20Data/data/unemployment.csv"
df = pd.read_csv(f1, encoding='unicode_escape', dtype={"id": str})
df.head()

import plotly.express as px
fig = px.choropleth(df, geojson=counties, locations='id', color='Population', color_continuous_scale="ice",
  range_color=(0, 150000), scope="usa", labels={'Population':'Population'})

fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()
# colors: ice, purples,

from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
  dtype = { "fips": str }
)

import plotly.express as px

fig = px.choropleth(df, geojson=counties, locations='fips', color='unemp',
  color_continuous_scale="Viridis", range_color=(0, 12), scope="usa",
  labels = { 'unemp': 'unemployment rate' }
)
fig.update_layout( margin = { "r": 0, "t": 0, "l": 0, "b": 0 } )
fig.show()