# -*- coding: utf-8 -*-
"""VisFinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V7ZsUXnrFVVdvP_u-uYt8mil1CXZcfEW
"""

# Research questions: 
#  Which factor of climate change is affecting the yield percentage the most? 
#  Which crop was affected most? 
# https://figshare.com/s/cde3e0d135b42cd7449f?file=31590557 

import pandas as pd 
import matplotlib.pyplot as plt 
import csv 

url = 'https://raw.githubusercontent.com/hMRZQ21/Vis/main/Projected_impacts_datasheet_11.24.2021.csv' 
df = pd.read_csv(url) 

# data = pd.DataFrame(df, columns = ['Projected yield (t/ha)', 'Current Average Temperature (dC)_area_weighted'], index = ['country 1', 'country 2']) 
# plt.rcParams["figure.figsize"] = (20, 20) 
# data.plot.barh() 
# plt.show() 

# fig = pd.histogram(df, x = 'Current Average Temperature (dC)_area_weighted')
# fig.show()

# country, year (non prediction), biggest crop (highest yielding), climate factors
# same thing, but in the future

#  projected yield of crops (4 kinds) + years (Baseline/ future midpoints)
  # projected yield vs current temp
  # projected yield vs local/ global delta T
  # projected yield vs current percip
  # projected yield vs CO2 ppm